import { Product, Review, Collection } from './types';

export const products: Product[] = [
  {
    id: 'swiss-coco-mademoiselle',
    name: 'Swiss Coco Mademoiselle',
    slug: 'swiss-coco-mademoiselle',
    tagline: 'Citrusy, bright and refreshing with a juicy touch.',
    price: 2350,
    image: '/products/swiss-gucci-flora.jpg',
    images: ['/products/swiss-gucci-flora.jpg'],
    category: 'women',
    fragranceFamily: 'Patchouli',
    volume: ['50ml'],
    description: 'A vibrant, sensual oriental fragrance opening with sparkling fresh orange and citrus, blossoming into a heart of pure rose and jasmine.',
    longDescription: 'Swiss Coco Mademoiselle represents the essence of a bold, free woman. An airy, feminine oriental composition characterized by surprising freshness. Sparks of vibrant orange and bergamot immediately awaken the senses, leading to a radiant heart of Grasse jasmine and morning rose petals. The base lingers with pure accents of Indonesian patchouli, Haitian vetiver, and white musk, creating a sillage of effortless sophistication perfectly suited for evening soirées and daily luxury across Pakistan.',
    notes: {
      top: ['Orange', 'Bergamot', 'Mandarin'],
      heart: ['Rose', 'Jasmine', 'Ylang-Ylang'],
      base: ['Patchouli', 'White Musk', 'Vetiver', 'Vanilla'],
    },
    rating: 4.9,
    reviewCount: 147,
    badge: 'bestseller',
    inStock: true,
  },
  {
    id: 'swiss-tobacco-vanille',
    name: 'Swiss Tobacco Vanille',
    slug: 'swiss-tobacco-vanille',
    tagline: 'Rich, warm and smooth with a sophisticated depth.',
    price: 2399,
    image: '/products/swiss-sauvage.jpg',
    images: ['/products/swiss-sauvage.jpg'],
    category: 'unisex',
    fragranceFamily: 'Tobacco',
    volume: ['50ml'],
    description: 'An opulent artisanal scent blending aromatic tobacco leaf, spiced heart notes, and creamy tonka bean with sweet vanilla.',
    longDescription: 'Swiss Tobacco Vanille is an opulent, warm, and iconic artisanal fragrance. Reminiscent of an elite English gentlemen’s club re-imagined with Swiss alpine precision. It opens with rich aromatic tobacco leaf and spicy accords that gracefully melt into creamy tonka bean, sweet vanilla, and rich cacao. Finishing with a luxurious dry wood sap and dried fruit accord, this fragrance delivers commanding projection and longevity lasting well over 16 hours.',
    notes: {
      top: ['Tobacco Leaf', 'Spiced Accords'],
      heart: ['Tonka Bean', 'Vanilla', 'Cacao', 'Tobacco Blossom'],
      base: ['Dried Fruits', 'Wood Sap'],
    },
    rating: 4.9,
    reviewCount: 147,
    badge: 'bestseller',
    inStock: true,
  },
  {
    id: 'swiss-janan',
    name: 'Swiss J. Janan',
    slug: 'swiss-janan',
    tagline: 'Crisp, fresh and juicy with a fruity brightness.',
    price: 2399,
    image: '/products/swiss-creed-aventus.jpg',
    images: ['/products/swiss-creed-aventus.jpg'],
    category: 'men',
    fragranceFamily: 'Bergamot',
    volume: ['50ml'],
    description: 'An iconic masculine signature opening with sparkling citrus and bergamot leading into a magnetic woody and musky dry-down.',
    longDescription: 'Swiss J. Janan is crafted for the modern gentleman who commands respect with poise. Opening with a crisp burst of zesty bergamot, red apple, and sun-drenched citrus, the heart unfolds into delicate floral accents of Moroccan jasmine and spicy pepper. The dry-down settles into an intoxicating blend of amber, cedarwood, and rich musk that projects cleanly throughout demanding work days and formal evenings.',
    notes: {
      top: ['Bergamot', 'Red Apple', 'Mandarin'],
      heart: ['Jasmine', 'Cardamom', 'Nutmeg'],
      base: ['Cedarwood', 'Musk', 'Amber'],
    },
    rating: 4.9,
    reviewCount: 147,
    badge: 'bestseller',
    inStock: true,
  },
  {
    id: 'swiss-blue-de-chanel',
    name: 'Swiss Blue De Chanel',
    slug: 'swiss-blue-de-chanel',
    tagline: 'Citrus, Mint, Pink Pepper, Grapefruit, Ginger, Jasmine.',
    price: 2299,
    image: '/products/swiss-sauvage.jpg',
    images: ['/products/swiss-sauvage.jpg'],
    category: 'men',
    fragranceFamily: 'Cedar',
    volume: ['50ml'],
    description: 'A timeless aromatic-woody composition with crisp citrus, fresh mint, and pink pepper over a bold trail of dry cedar.',
    longDescription: 'Swiss Blue De Chanel is an ode to masculine freedom expressed in an aromatic-woody fragrance with a captivating trail. A timeless scent housed in a sleek 50ml flacon. It opens with an invigorating burst of fresh grapefruit, crisp mint, and pink pepper before revealing warm cedar notes and New Caledonian sandalwood. A versatile masterpiece that transitions seamlessly from executive boardroom meetings to intimate evening dinners.',
    notes: {
      top: ['Grapefruit', 'Lemon', 'Mint', 'Pink Pepper'],
      heart: ['Ginger', 'Nutmeg', 'Jasmine', 'Iso E Super'],
      base: ['Incense', 'Vetiver', 'Cedar', 'Sandalwood', 'Patchouli'],
    },
    rating: 4.9,
    reviewCount: 147,
    badge: 'bestseller',
    inStock: true,
  },
  {
    id: 'swiss-tuscan-leather',
    name: 'Swiss Tom Ford Tuscan Leather',
    slug: 'swiss-tuscan-leather',
    tagline: 'Bold, fruity and inviting with a sweet richness.',
    price: 2450,
    image: '/products/swiss-dunhill-desire-red.jpg',
    images: ['/products/swiss-dunhill-desire-red.jpg'],
    category: 'unisex',
    fragranceFamily: 'Saffron',
    volume: ['50ml'],
    description: 'Exotic, spicy and luxurious with dark leather, night-blooming jasmine, and sweet wild raspberry.',
    longDescription: 'Swiss Tom Ford Tuscan Leather merges primal, artisanal leather with night-blooming jasmine and black suede for a raw yet refined olfactory signature. The initial aroma surprises with a tantalizing touch of sweet wild raspberry, thyme, and saffron before transitioning into opulent resinous olibanum and warm amber. An undeniably magnetic Extrait formulation that leaves an unforgettable impression.',
    notes: {
      top: ['Raspberry', 'Saffron', 'Thyme'],
      heart: ['Olibanum', 'Night Jasmine'],
      base: ['Leather', 'Black Suede', 'Amber', 'Woody Notes'],
    },
    rating: 4.9,
    reviewCount: 147,
    badge: 'bestseller',
    inStock: true,
  },
  {
    id: 'swiss-gucci-flora',
    name: 'Swiss Gucci Flora',
    slug: 'swiss-gucci-flora',
    tagline: 'Soft, floral and feminine with a romantic touch.',
    price: 2399,
    image: '/products/swiss-gucci-flora.jpg',
    images: ['/products/swiss-gucci-flora.jpg'],
    category: 'women',
    fragranceFamily: 'Sandalwood',
    volume: ['50ml'],
    description: 'Fresh, zesty and vibrant with a bright floral bouquet of white gardenia, joyful pear blossom, and solar jasmine.',
    longDescription: 'Swiss Gucci Flora is a delightfully uplifting floral bouquet built around the glorious white gardenia blossom. Admired since the dawn of time for its splendour and reputed mystical elixir properties, the white gardenia note is blended with solar Grandiflorum jasmine absolute. The modern floral signature is introduced by a cheerful pear blossom accord and sweetened by a delicate touch of brown sugar.',
    notes: {
      top: ['Pear Blossom', 'Red Berries', 'Italian Mandarin'],
      heart: ['White Gardenia', 'Jasmine', 'Frangipani'],
      base: ['Brown Sugar', 'Patchouli'],
    },
    rating: 4.9,
    reviewCount: 147,
    badge: 'bestseller',
    inStock: true,
  },
  {
    id: 'swiss-creed-aventus',
    name: 'Swiss Creed Aventus',
    slug: 'swiss-creed-aventus',
    tagline: 'Juicy, vibrant and energetic with a tropical edge.',
    price: 2399,
    image: '/products/swiss-creed-aventus.jpg',
    images: ['/products/swiss-creed-aventus.jpg'],
    category: 'men',
    fragranceFamily: 'Musk',
    volume: ['50ml'],
    description: 'The legendary celebration of strength and success featuring French apple, pineapple, smoky birch, and opulent ambergris.',
    longDescription: 'Swiss Creed Aventus is an illustrious celebration of strength, vision, and success. Inspired by the dramatic life of historic emperors, this fragrance opens with tantalizing top notes of crisp blackcurrant, Italian bergamot, French apples, and royal pineapple. The woody heart combines smoky birch, patchouli, and clean jasmine, drying down into an enduring base of oakmoss, ambergris, and vanilla that commands royal attention.',
    notes: {
      top: ['Pineapple', 'Bergamot', 'Blackcurrant', 'Apple'],
      heart: ['Birch', 'Patchouli', 'Moroccan Jasmine', 'Rose'],
      base: ['Musk', 'Oakmoss', 'Ambergris', 'Vanilla'],
    },
    rating: 4.9,
    reviewCount: 147,
    badge: 'bestseller',
    inStock: true,
  },
  {
    id: 'swiss-bomb-shell',
    name: 'Swiss Bomb Shell',
    slug: 'swiss-bomb-shell',
    tagline: 'Spicy, vibrant and invigorating.',
    price: 2250,
    image: '/products/swiss-bomb-shell.jpg',
    images: ['/products/swiss-bomb-shell.jpg'],
    category: 'women',
    fragranceFamily: 'Vanilla',
    volume: ['50ml'],
    description: 'A sparkling, glamorous fruity-floral cocktail bursting with purple passionfruit, Shangri-la peony, and Madagascar vanilla.',
    longDescription: 'Swiss Bomb Shell is a dazzling burst of confidence and glamour. This fragrance opens with a sparkling citrus-fruit cocktail of Brazilian purple passionfruit, grapefruit, and sweet strawberry. The heart blooms with the clean floral aroma of Shangri-la yellow peony and Italian sun-drenched pine, resting on a velvety base of Madagascar vanilla orchid and warm oakmoss that projects with irresistible charm.',
    notes: {
      top: ['Passionfruit', 'Grapefruit', 'Pineapple', 'Tangerine'],
      heart: ['Peony', 'Vanilla Orchid', 'Red Berries', 'Jasmine'],
      base: ['Musk', 'Woody Notes', 'Oakmoss'],
    },
    rating: 4.9,
    reviewCount: 147,
    badge: 'bestseller',
    inStock: true,
  },
  {
    id: 'swiss-sauvage',
    name: 'Swiss Sauvage',
    slug: 'swiss-sauvage',
    tagline: 'Fresh, zesty and uplifting with a vibrant energy.',
    price: 2750,
    image: '/products/swiss-sauvage.jpg',
    images: ['/products/swiss-sauvage.jpg'],
    category: 'men',
    fragranceFamily: 'Ambroxan',
    volume: ['50ml'],
    description: 'A radically fresh and powerful composition unleashed by radiant Calabrian bergamot and a noble woody trail of Ambroxan.',
    longDescription: 'Swiss Sauvage is a radically fresh composition dictated by untamed nature under a wide blue sky. Radiant top notes burst with the juicy freshness of Reggio di Calabria bergamot, while Sichuan pepper and lavender provide a spicy, aromatic kick. The fragrance unleashes a powerful amber-woody trail of noble Ambroxan that endures through warm Pakistani summers with unmatched longevity and magnetic projection.',
    notes: {
      top: ['Calabrian Bergamot', 'Pepper'],
      heart: ['Sichuan Pepper', 'Lavender', 'Pink Pepper', 'Vetiver', 'Patchouli'],
      base: ['Ambroxan', 'Cedar', 'Labdanum'],
    },
    rating: 4.9,
    reviewCount: 147,
    badge: 'bestseller',
    inStock: true,
  },
  {
    id: 'swiss-dunhill-red',
    name: 'Swiss Dunhill Red',
    slug: 'swiss-dunhill-red',
    tagline: 'Crisp, fruity and fresh with a juicy sweetness.',
    price: 2250,
    image: '/products/swiss-dunhill-desire-red.jpg',
    images: ['/products/swiss-dunhill-desire-red.jpg'],
    category: 'men',
    fragranceFamily: 'Wood',
    volume: ['50ml'],
    description: 'An alluring oriental-woody fragrance fueled by crisp red apple, neroli, teakwood, and seductive vanilla musk.',
    longDescription: 'Swiss Dunhill Red is an exhilarating oriental-woody scent designed for the passionate and self-assured man. The fragrance bursts open with crisp notes of red apple, sparkling lemon, neroli, and fresh bergamot. The heart introduces teakwood, rose, and patchouli, creating a warm romantic core before settling into an irresistible dry-down of precious vanilla, labdanum, and sensual musk.',
    notes: {
      top: ['Apple', 'Lemon', 'Bergamot', 'Neroli'],
      heart: ['Teak Wood', 'Rose', 'Patchouli'],
      base: ['Vanilla', 'Musk'],
    },
    rating: 4.9,
    reviewCount: 147,
    badge: 'bestseller',
    inStock: true,
  },
];

export const reviews: Review[] = [
  {
    id: '1',
    name: 'Muhammad Usman (Lahore)',
    avatar: '/avatars/avatar-1.jpg',
    rating: 5,
    date: '2026-03-12',
    text: 'Swiss Sauvage has unmatched projection! In Lahore\'s warm weather, it easily lasts over 14 hours. The COD delivery arrived in 2 days and the 50ml bottle packaging feels pure luxury.',
    verified: true,
  },
  {
    id: '2',
    name: 'Ayesha Malik (Karachi)',
    avatar: '/avatars/avatar-2.jpg',
    rating: 5,
    date: '2026-02-28',
    text: 'Swiss Gucci Flora is pure elegance. Fresh, floral, and I get compliments constantly at university and weddings. The 50ml bottle is super chic and fits easily in my handbag.',
    verified: true,
  },
  {
    id: '3',
    name: 'Bilal Ahmed (Islamabad)',
    avatar: '/avatars/avatar-3.jpg',
    rating: 5,
    date: '2026-02-15',
    text: 'The Creed Aventus impression is spot on! Smoky birch with crisp pineapple. The quality easily rivals perfumes 5x the price. Cash on delivery was seamless.',
    verified: true,
  },
  {
    id: '4',
    name: 'Fatima Noor (Rawalpindi)',
    avatar: '/avatars/avatar-4.jpg',
    rating: 5,
    date: '2026-01-20',
    text: 'Swiss Bomb Shell is my absolute favorite. Ordered via COD and parcel reached in pristine condition. The sweet fruity sillage lasts all day on clothes.',
    verified: true,
  },
  {
    id: '5',
    name: 'Hamza Khan (Peshawar)',
    avatar: '/avatars/avatar-5.jpg',
    rating: 5,
    date: '2026-01-08',
    text: 'Swiss Tobacco Vanille is warm, rich, and sophisticated. The sillage is remarkable — people at dinner always ask which high-end niche perfume I\'m wearing.',
    verified: true,
  },
  {
    id: '6',
    name: 'Zainab Tariq (Faisalabad)',
    avatar: '/avatars/avatar-6.jpg',
    rating: 5,
    date: '2025-12-22',
    text: 'Swiss Coco Mademoiselle is my new daily signature. Fresh citrus opening with a deep patchouli finish that lingers all day. Truly premium Swiss quality!',
    verified: true,
  },
];

export const collections: Collection[] = [
  {
    id: 'bestsellers',
    name: 'Bestsellers',
    slug: 'bestsellers',
    description: 'Our most loved fragrances, chosen by thousands of discerning customers across Pakistan.',
    image: '/products/swiss-sauvage.jpg',
    productIds: ['swiss-sauvage', 'swiss-creed-aventus', 'swiss-gucci-flora'],
  },
  {
    id: 'evening-luxe',
    name: 'Evening Luxe',
    slug: 'evening-luxe',
    description: 'Captivating scents designed for nights that deserve to be remembered.',
    image: '/products/swiss-dunhill-desire-red.jpg',
    productIds: ['swiss-tobacco-vanille', 'swiss-tuscan-leather', 'swiss-dunhill-red'],
  },
  {
    id: 'fresh-collection',
    name: 'Fresh & Invigorating',
    slug: 'fresh-collection',
    description: 'Crisp, clean fragrances inspired by the pristine Swiss landscape.',
    image: '/products/swiss-creed-aventus.jpg',
    productIds: ['swiss-blue-de-chanel', 'swiss-janan', 'swiss-sauvage'],
  },
  {
    id: 'gift-sets',
    name: 'Gift Sets',
    slug: 'gift-sets',
    description: 'Luxuriously packaged 50ml sets that make every occasion unforgettable.',
    image: '/products/swiss-bomb-shell.jpg',
    productIds: ['swiss-coco-mademoiselle', 'swiss-bomb-shell'],
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return products.find(p => p.slug === slug);
}

export function getProductsByCategory(category: string): Product[] {
  if (category === 'all') return products;
  return products.filter(p => p.category === category);
}

export function getFeaturedProducts(): Product[] {
  return products.filter(p => p.badge === 'bestseller' || p.badge === 'limited');
}

export function getCollectionBySlug(slug: string): Collection | undefined {
  return collections.find(c => c.slug === slug);
}

export function getCollectionProducts(collection: Collection): Product[] {
  return collection.productIds
    .map(id => products.find(p => p.id === id))
    .filter((p): p is Product => p !== undefined);
}

